### ISSUE TITLE
Classic: Frame messages on login

### ISSUE THREAD

**Issue by panoplybez** [Kiatra/BlizzMove#63]
When logging into Classic WoW, I see the following frame messages printed to chat, every time:

BlizzMove: Could not find frame ( Build: 38386 | Version: 11307 ): FriendsListFrameScrollFrame 
BlizzMove: Could not find frame ( Build: 38386 | Version: 11307 ): QuickJoinScrollFrame 
BlizzMove: Could not find frame ( Build: 38386 | Version: 11307 ): IgnoreListFrameScrollFrame 

I have not changed any of the default addon settings, so every frame available in the config is enabled.

Running 3.0.13 Classic version

**Comment by zaCade** [comment]
Just out of curiousity from my end here, how long have you been using BlizzMove.
Because if you have been using it for a longer period. Have these 'errors' always showed up or did they only start recently?

These errors aren't breaking the addon so nothing to worry there, will fix them though just gunna wait for your answer, that'll give me some information i need.

**Comment by panoplybez** [comment]
For Classic I've only been using it about a month I'd say. They've been showing up since I installed it for classic yes - so at least for the past couple of addon version updates. I'm fairly certain that I didn't accidentally try to install the retail version of it :D

**Comment by zaCade** [comment]
Alright thanks for the information,
And even if you wouldve installed the retail version, the only diffrence between the two is the interface version of the addon. Functionality wise exactly the same.

Ill push out a fix for this soon.

**Comment by zaCade** [comment]
Fixed it with v3.0.14.

**Comment by panoplybez** [comment]
nice! thank you!
